export const routeNames = {
  encryptNotes: 'encryptNotes',
  noteDetails: 'noteDetails',
  notebookForm: 'notebookForm',
  notebook: 'notebook',
  encryptFiles: 'encryptFiles',
  folder: 'folder',
  folderForm: 'folderForm',
  renameFileForm: 'renameFileForm',
  passwords: 'passwords',
  passwordForm: 'passwordForm',
  settings: 'settings',
  plainText: 'plainText',
  passwordGenerator: 'passwordGenerator',
};
