export const routeNames = {
  folders: 'folders',
  folder: 'folder',
  folderForm: 'folderForm',
  renameFileForm: 'renameFileForm',
  takePhoto: 'takePhoto',
  noteDetails: 'noteDetails',
  passwords: 'passwords',
  passwordForm: 'passwordForm',
  settings: 'settings',
  plainText: 'plainText',
  passwordGenerator: 'passwordGenerator',
  backup: 'backup',
  donation: 'donation',
};
